# Your workflow name
name: Deploy TO Heroku

#Run workflow on every push to main branch
on:
  push:
    branches: [main]

#Your workflow jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Checkout your repository
      - name: Checkout
        uses: actions/checkout@v2

### ! IMPORTANT PART !###
      - name: Build, push and Release a Docker Container to Heroku # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # Github action name (leave as it is)
        with:
          #Below you must provide the variable for your heroku app
          
          # The email address associated with your heroku account
          email: ${{secrets.HEROKU_EMAIL}}

          #Heroku api key
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}

          #Heroku App Name
          heroku_app_name : ${{secrets.HEROKU_APP_NAME}}

          #Docker Directory
          dockerfile_directory: ./
          
          #Docker File Name
          dockerfile_name : Dockerfile

          #Additional Options of docker build commands
          #default: ""
          docker_options: "--no-cache--"

          #Select the process type for which you want the docker container to be uploaded
          # By default, this argument is set to "web"
          process_type: web

### ! IMPORTANT PART ! ###